<h2 class="text-center">Catégories</h2>
<!-- DEBUT formulaire ajout catégorie -->
<fieldset class="wrapper-add-category">
	<legend>Ajouter une catégorie :</legend>
	<div class="row">
	<?php require('views/admin/category/display-form-add.phtml'); ?>
	</div>
</fieldset>
<!-- FIN formulaire ajout catégorie -->
<!-- DEBUT afficahge liste des catégories -->
<fieldset class="wrapper-list-categories">
	<legend>Liste des catégories :</legend>
	<div class="wrapper-title-category row">
		<div class="col-sm-3">Titre</div>
		<div class="col-sm-7">Description </div>
	</div>
	<div class="wrapper-categories">
		<?php require('apps/admin/display-categories.php'); ?>
	</div>
</fieldset>
<!-- FIN afficahge liste des catégories -->