<h2 class="text-center">Utilisateurs</h2>
<!-- DEBUT afficahge liste des utilisateurs -->
<fieldset class="wrapper-list-users">
	<legend>Liste des utilisateurs :</legend>
	<div class="wrapper-title-user row">
		<div class="col-sm-1">Avatar</div>
		<div class="col-sm-3">Login</div>
		<div class="col-sm-4">Adresse mail</div>
		<div class="col-sm-2">Rang</div>
	</div>
	<div class="wrapper-users">
	<?php require('apps/admin/display-users.php'); ?>
	</div>
</fieldset>
<!-- FIN afficahge liste des utilisateurs -->