<!-- Formulaire de modification du rang d'un utilisateur dans l'administration -->
<form action="admin_user" method="post" class=" col-md-8 col-md-offset-2 form-inline js-user-form-modif">
	<input name="id" value="<?=$user->getId()?>" hidden id="user-modif-id-<?=$user->getId()?>">
	<div class="form-group">
		<label for="user-modif-permission-<?=$user->getId()?>" class="sr-only">Nouvelle permission :</label>
		<select class="form-control" id="user-modif-permission-<?=$user->getId()?>" name="permission">
			<option value="1">Administrateur</option>
			<option value="2">Modérateur</option>
			<option value="3" selected>Membre</option>
		</select>
	</div>
	<div class="form-group">
		<button name="modif" type="submit" class="btn btn-info btn-valid-modif-user">Modifier</button>
		<button class="btn btn-default btn-cancel-modif-user">Annuler</button>
	</div>
	<div class="bg-danger" id="error-modif-user-<?=$user->getId()?>"></div>
</form>