<form class="form-horizontal" method="POST">
  <div class="form-group form-group-lg">
	    <label class="col-sm-2 control-label" for="formGroupInputLarge">Nouveau topic</label>
	    <div class="col-sm-10">
	      <input class="form-control" type="text" id="newtopic" name="newtopic" autofocus>
	    </div>
	</div>
	<div>
		<input type="submit" class="btn btn-default" name="validation" />
	</div>
</form>