<form class="form-horizontal" method="POST" action="post">
	<button name="btt-createPost" id="buttonEdit" class="js-button-create">
		<span class="glyphicon glyphicon-pencil">
		</span>
	</button>
		<div  class="inv" id="<?$post->getId()?>">
		  <div class="form-group form-group-lg">
				<div class="row">
				    <label class="col-sm-2 control-label" for="formGroupInputLarge">Titre (optionnel) </label>
				    <div class="col-sm-10">
				      <input class="form-control" type="text" id="newtitle" name="newtitle" autofocus>
				      
				    </div>
				</div>
				<div class="row">
				    <label class="col-sm-2 control-label" for="formGroupInputLarge">Nouveau message </label>
				      <div class="col-sm-10">
				    	<textarea class="form-control" rows="3" name="newpost"></textarea>
					</div>
				</div>
				<div>
					<input type="submit" class="btn btn-default" name="validation" />

				</div>
			</div>
		</div>
			
				<div>
					<input name="idtopic" value="<?=$topic->getId()?>" hidden>
					<input name="idcategory" value="<?=$topic->getIdCategory()?>" hidden>
				</div>
			
	
</form>