<form action="admin/admin_user" method="post" class=" col-md-8 col-md-offset-2 form-inline js-user-form-modif">
	<input name="id" value="<?=$user->getId()?>" hidden>
	<div class="form-group">
		<label for="user-modif-permission" class="sr-only">Nouvelle permission :</label>
		<select type="text" class="form-control" id="user-modif-permission" name="permission" placeholder="Titre de la catégorie">
			<option value="1">Administrateur</option>
			<option value="2">Modérateur</option>
			<option value="3">Membre</option>
		</select>
	</div>
	<div class="form-group">
		<button name="modif" type="submit" class="btn btn-info">Modifier</button>
		<button class="btn btn-default btn-cancel-modif-user">Annuler</button>
	</div>
</form>