<!-- Affichage d'un utilisateur dans l'administration -->
<div class="row" id="user-<?=$user->getId()?>">
	<div class="col-sm-1 vmiddle">
		<?php if($user->getAvatar() != ""){ ?>
		<img src="public/img/<?=htmlentities($user->getAvatar())?>" class="img-responsive center-block">
		<?php } ?>
	</div><!--
	--><div class="col-sm-3 vmiddle"><?=htmlentities($user->getLogin())?> 
	<?php if($endBan != 0){ ?>
		<span class="text-danger"> (banni)<br /><?=$endBan?></span>
	<?php } ?>
	</div><!--
	--><div class="col-sm-4 vmiddle"><?=htmlentities($user->getEmail())?></div><!--
	--><div class="col-sm-2 vmiddle"><?=htmlentities($manager->getPermissionLevel($user->getIdPermission()))?></div><!--
	--><div class="col-sm-1 vmiddle"><button class="btn btn-info btn-sm btn-modif-user" title="Modifier le rang"><span class="glyphicon glyphicon-pencil"></span></button></div><!--
	--><?php if($manager->getPermissionLevel($user->getIdPermission()) != "admin" && $endBan == 0){ ?><!--
	--><div class="col-sm-1 vmiddle"><button class="btn btn-warning btn-sm btn-ban-user" title="Bannir l'utilisateur"><span class="glyphicon glyphicon-remove"></span></button></div>
	<?php } ?>
</div>
<div class="row">
<?php require('views/display-admin-user-form-modif.phtml'); ?>
<?php if($manager->getPermissionLevel($user->getIdPermission()) != "admin"){ 
	require('views/display-admin-user-form-ban.phtml');
} ?>
</div>