<h2 class="text-center">Messages signalés</h2>
<!-- DEBUT afficahge liste des messages signalés -->
<fieldset class="wrapper-list-posts">
	<div class="wrapper-title-post row">
		<div class="col-sm-2">Titre</div>
		<div class="col-sm-4">Message</div>
		<div class="col-sm-2">Auteur</div>
		<div class="col-sm-3">Topic</div>
		<div class="col-sm-1">Lien</div>
	</div>
	<div class="wrapper-posts">
		<?php require('apps/display-admin-posts.php'); ?>
	</div>
</fieldset>
<!-- FIN afficahge liste des messages signalés -->