<form action="admin/admin_post" method="post" class="js-post-form-valid col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
	<input name="id" value="<?=$id?>" hidden>
	<div class="form-group">
		<label>Valider le message (ne supprime pas le message) : </label>
		<button name="valid" type="submit" class="btn btn-default">Oui</button>
		<button class="btn btn-default btn-cancel-valid-post">Non</button>
	</div>
</form>