<form action="admin/admin_category" method="post" class="js-category-form-delete col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
	<input name="id" value="<?=$id?>" hidden>
	<div class="form-group">
		<label>Supprimer la catégorie : <?=$name?></label>
		<button name="delete" type="submit" class="btn btn-default">Oui</button>
		<button class="btn btn-default btn-cancel-delete-category">Non</button>
	</div>
</form>