<form action="admin/admin_post" method="post" class="js-post-form-modif col-md-8 col-md-offset-2">
	<input name="id" value="<?=$id?>" hidden>
	<div class="form-group">
		<label for="post-modif-title" class="sr-only">Titre du message :</label>
		<input type="text" class="form-control" id="post-modif-title" name="title" value="<?=$title?>" placeholder="Titre du message">
	</div>
	<div class="form-group">
		<label for="post-modif-content" class="sr-only">Contenu du message :</label>
		<textarea type="text" class="form-control" id="post-modif-content" name="content" placeholder="Contenu du message" rows="5"><?=$content?></textarea>
	</div>
	<div class="form-group">
		<button name="modif" type="submit" class="btn btn-info">Modifier</button>
		<button class="btn btn-default btn-cancel-modif-post">Annuler</button>
	</div>
</form>