<!-- Affichage d'un post dans l'administration -->
<div class="row" id="post-<?=$post->getId()?>">
	<div class="col-sm-2 vmiddle"><?=htmlentities($post->getTitle())?></div><!--
	--><div class="col-sm-4 vmiddle"><?=htmlentities($post->getContent())?></div><!--
	--><div class="col-sm-2 vmiddle"><a href="profil/<?=htmlentities($post->getAuthor()->getLogin())?>"><?=htmlentities($post->getAuthor()->getLogin())?></a></div><!--
	--><div class="col-sm-3 vmiddle"><?=htmlentities($post->getTopic()->getName())?></div><!--
	--><div class="col-sm-1 vmiddle"><a href="<?=$linkPost?>">Voir</a></div>
</div>
<div class="row">
	<div class="col-sm-1 vmiddle"><button class="btn btn-success btn-sm btn-valid-post" title="Valider le message"><span class="glyphicon glyphicon-ok"></span></button></div><!--
	--><div class="col-sm-1 vmiddle"><button class="btn btn-info btn-sm btn-modif-post" title="Modifier le message"><span class="glyphicon glyphicon-pencil"></span></button></div><!--
	--><div class="col-sm-1 vmiddle"><button class="btn btn-danger btn-sm btn-delete-post" title="Supprimer le message"><span class="glyphicon glyphicon-remove"></span></button></div><!--
--><div class="col-sm-9"></div>
</div>
<div class="row">
	<?php require('views/display-admin-post-form-valid.phtml'); ?>
	<?php require('views/display-admin-post-form-modif.phtml'); ?>
	<?php require('views/display-admin-post-form-delete.phtml'); ?>
</div>