<form action="admin_category" method="post" class="js-category-form-modif col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
	<input name="id" value="<?=$category->getId()?>" hidden  id="category-modif-id-<?=$category->getId()?>">
	<div class="form-group">
		<label for="category-modif-name" class="sr-only">Titre de la catégorie :</label>
		<input type="text" class="form-control" id="category-modif-name-<?=$category->getId()?>" name="name" value="<?=htmlentities($category->getName())?>" placeholder="Titre de la catégorie">
	</div>
	<div class="form-group">
		<label for="category-modif-description" class="sr-only">Description de la catégorie :</label>
		<textarea type="text" class="form-control" id="category-modif-description-<?=$category->getId()?>" name="description" placeholder="Description de la catégorie" rows="5"><?=htmlentities($category->getDescription())?></textarea>
	</div>
	<div class="form-group">
		<button name="modif" type="submit" class="btn btn-info btn-valid-modif-category">Modifier</button>
		<button class="btn btn-default btn-cancel-modif-category">Annuler</button>
	</div>
</form>