<!-- Formulaire de suppression d'une catégorie dans l'administration -->
<form action="admin_category" method="post" class="js-category-form-delete col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
	<input name="id" value="<?=$category->getId();?>" hidden>
	<div class="form-group">
		<label>Supprimer la catégorie : <?=htmlentities($category->getName());?></label>
		<button name="delete" type="submit" class="btn btn-default">Oui</button>
		<button class="btn btn-default btn-cancel-delete-category">Non</button>
	</div>
	<div class="bg-danger" id="error-delete-cat-<?=$category->getId()?>"></div>
</form>