<div class="wrapper-post row">
	<div class="col-sm-2 vmiddle"><?=htmlentities($title)?></div><!--
	--><div class="col-sm-3 vmiddle"><?=htmlentities($content)?></div><!--
	--><div class="col-sm-2 vmiddle"><a href="profil/<?=$user?>"><?=htmlentities($user)?></a></div><!--
	--><div class="col-sm-2 vmiddle"><?=htmlentities($topic)?></div><!--
	--><div class="col-sm-1 vmiddle"><a href="<?=$category?>/<?=$topic?>/#<?=$id?>">Voir</a></div><!--
	--><div class="col-sm-1 vmiddle"><button class="btn btn-success btn-sm btn-valid-post" title="Valider le message"><span class="glyphicon glyphicon-ok"></span></button></div><!--
	--><div class="col-sm-1 vmiddle"><button class="btn btn-danger btn-sm btn-delete-post" title="Supprimer le message"><span class="glyphicon glyphicon-remove"></span></button></div>
	<?php require('views/display-admin-post-form-delete.phtml'); ?>
	<?php require('views/display-admin-post-form-valid.phtml'); ?>
</div>