<form action="" method="post" class="js-category-form-modif col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
	<input name="category-modif-id" value="<?=$id?>" hidden>
	<div class="form-group">
		<label for="category-modif-name" class="sr-only">Titre de la catégorie :</label>
		<input type="text" class="form-control" id="category-modif-name" name="category-modif-name" value="<?=$name?>" placeholder="Titre de la catégorie">
	</div>
	<div class="form-group">
		<label for="category-modif-description" class="sr-only">Description de la catégorie :</label>
		<textarea type="text" class="form-control" id="category-modif-description" name="category-modif-description" placeholder="Description de la catégorie" rows="5"><?=$description?></textarea>
	</div>
	<div class="form-group">
		<button name="modif" type="submit" class="btn btn-info">Modifier</button>
	</div>
</form>