<form class="form-horizontal" method="POST" action="post">
	<div class="form-group form-group-lg">
		<div class="row">
			<label class="col-sm-2 control-label" for="formGroupInputLarge"><?=htmlentities($post->getTitle())?></label>
			<div class="col-sm-10">
				<input class="form-control" type="text" id="uptitle" name="uptitle" autofocus>

			</div>
		</div>
		<div class="row">
			<label class="col-sm-2 control-label" for="formGroupInputLarge"><?=htmlentities($post->getContent())?></label>
			<div class="col-sm-10">
				<textarea class="form-control" rows="3" name="uppost"></textarea>
			</div>
		</div>
	</div>
	<div class="row">
		<div>
			<input name="idtopic" value="<?=$topic->getId()?>" hidden>
			<input name="idcategory" value="<?=$topic->getIdCategory()?>" hidden>
			<input type="submit" class="btn btn-default" name="validation" id="validation" />
		</div>
	</div>
</form>
