<div class="row forum">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 autor">
	<!-- 	nom de l'auteur nbre d'intervention-->
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 rules">
		<?=htmlentities($topic->getName())?> <?=htmlentities($topic->getAuthor()->getLogin())?>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 infolastpost">
		<!-- dernier auteur date -->
	</div>
</div>

