<div class="row listPostSingle">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 autor">
		<img src="public/img/<?=htmlentities($post->getAuthor()->getAvatar())?>" alt="">
		<div><?=$author?></div>
		<?php require ('apps/remotePost.php');?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12  post <?=$delstyle?>">
		<?=htmlentities($post->getContent())?> 
	</div>
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 infolastpost">
		
	</div>
</div>