<?php require('apps/search.php'); ?>
<div class="row forum">
	<div class="addTopic">
			<?php require('apps/remoteTopic.php');?>
		</div>
	
	<div class="col-xs-12">

		<h3 class="glyphicon glyphicon-pushpin"><a href="category/<?=htmlentities(str_replace(' ', '_', $category->getName()))?>"><?=$category->getName()?></a></h3>
		<p><?=htmlentities($category->getDescription())?></p>


		<div class="searchResult">
			<?php require ('apps/display-listTopics.php');?>
		</div>

	</div>
</div>

