<div class="row listPostSingle">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 autor">
		<?php require ('apps/remotePost.php');?>
		<img src="public/img/<?=htmlentities($post->getAuthor()->getAvatar())?>" alt="">
		<a href="profil/<?=str_replace(" ","_",(htmlentities($post->getAuthor()->getLogin())))?>"><?=htmlentities($post->getAuthor()->getLogin())?></a>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 rules">
		<?=htmlentities($post->getContent())?> 
	</div>
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 infolastpost"></div>
</div>