<div class="row forum">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 autor">
		<a href="profil/<?=htmlentities($topic->getAuthor()->getLogin())?>"><?=htmlentities($topic->getAuthor()->getLogin())?></a>
		<img src="public/img/<?=htmlentities($topic->getAuthor()->getAvatar())?>" alt="">
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 rules">
		<a href="<?=htmlentities(str_replace(' ', '_', ($category->getName()).'/'.$topic->getName()))?>">
			<?=htmlentities($topic->getName())?>
		</a>
		
	</div>
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 infolastpost">
		<!-- dernier auteur date -->
	</div>
</div>

