<div class="row forum">
	<div class="col-xs-12">
		<h3><a href="category/<?=htmlentities($category->getName())?>"><?=$category->getName()?></a></h3>
	
		<?php require ('apps/display-listTopics.php');?>
	</div>
</div>


<!-- formulaire ajout topic -->
<?php if($page != "home"){ ?>
<div class="wrapper-topic-form-add">
	<?php require('views/display-category-topic-form-add.phtml');?>
</div>
<?php } ?>