<section class="profil row">
<h2><span class="glyphicon glyphicon-user"></span><?=htmlentities(ucfirst($login))?> <em>(<?=$PermissionLevel?>)</em></h2>

<div class="col-xs-4 col-md-5">
	<div class="profItem">
		<img class="thumbnail" src="public/img/<?=$avatar?>" alt="">
	</div>

	
</div>

<div class="col-xs-8 col-md-7">	
	<div class="profItem">
		<h4><span class="glyphicon glyphicon-star"></span>Inscrit depuis:</h4>
		<p> <?=htmlentities($date_register)?></p>
	</div>
	<div class="profItem">
		<h4><span class="glyphicon glyphicon-star"></span>Description:</h4>
		<p> <?=htmlentities($description)?></p>
	</div>
	<div class="profItem">
		<h4><span class="glyphicon glyphicon-star"></span>Date de naissance : <?=$birthdate?></h4>
	</div>
</div>
</section>
