<!-- <form action="memberpost" method="post" class="js-category-form-add col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
	<div class="form-group">
		<label for="category-add-name" class="sr-only">Titre (optionnel):</label>
		<input type="text" class="form-control" name="name" id="post-add-name" value="" placeholder="Titre">
	</div>
	<div class="form-group">
		<button name="create" type="submit" class="btn btn-success">Ajouter</button>
	</div>
	<div class="bg-danger"></div>
	<div class="bg-success"></div>
</form> -->