<section class="profil row">
<h2><span class="glyphicon glyphicon-user"></span><?=htmlentities(ucfirst($user->getLogin()))?> <em>(<?=$PermissionLevel?>)</em></h2>

<div class="col-xs-4 col-md-5">
	<div class="profItem">
		<img class="thumbnail" src="public/img/<?=$user->getAvatar()?>" alt="">
	</div>
</div>

<div class="col-xs-8 col-md-7">	
	<div class="profItem">
		<h4><span class="glyphicon glyphicon-star"></span>Inscrit depuis:</h4>
		<p> <?=htmlentities($user->getDateRegister())?></p>
	</div>
	<div class="profItem">
		<h4><span class="glyphicon glyphicon-star"></span>Description:</h4>
		<p> <?=htmlentities($description)?></p>
	</div>
	<div class="profItem">
		<h4><span class="glyphicon glyphicon-star"></span>Date de naissance : <?=$birthdate?></h4>
	</div>
</div>
</section>
<section class="contrib row">
<h2><span class="glyphicon glyphicon-pencil"></span>Les topics crées <em>(<?=$countT?>)</em></h2>
<div class="contribArt">
	 <?php require('apps/contribution_topic.php'); ?>
</div>
</section>
<section class="contribArt">
<h2><span class="glyphicon glyphicon-thumbs-up"></span>Participation<em>(<?=$countP?>)</em></h2>
<div class="contribArt">
	 <?php require('apps/contribution_post.php'); ?>
</div>
</section>
