<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Se connecter <span class="caret"></span></a>
<ul class="dropdown-menu">
	<li class="dropdown-login">
		<form action="login" method="post" class="form-login-nav navbar-form js-loginform">
			<div class="form-group">
				<label class="sr-only" for="login">Login</label>
				<input type="login" name="login" class="form-control" id="login" placeholder="login" value="<?=$login?>">
			</div>
			<div class="form-group">
				<label class="sr-only" for="password">Mot de passe</label>
				<input type="password" name="password" class="form-control" id="password" placeholder="Mot de passe">
			</div>
			<div class="form-group bg-danger"><?=htmlentities($error)?></div>
			<div class="form-group">
				<button id="btn-test" type="submit" class="btn btn-default btn-form-login">Se connecter</button>
			</div>
		</form>
	</li>
</ul>