<section class="profil">
<h2><span class="glyphicon glyphicon-user"></span>Votre profil</h2>
<div class="message">
	<div class="bg-danger"><p><?=$error?></p></div>
	<div class="bg-success"><p><?=$success?></p></div>

</div>
<div class="col-md-4">
	<img class="thumbnail" src="img/<?=$avatar?>" alt="">
	<form id="avatar" method="post" enctype="multipart/form-data">
	<div class="form-group">
		<input name="changeavatar" type="file">
		<input type="hidden" name="MAX_FILE_SIZE" value="100000">
		<button class="btn btn-danger"><span class="glyphicon glyphicon-ok-circle"></span></button>
	</div>
</div>

<div class="col-md-8">	
<h4><span class="glyphicon glyphicon-star"></span>Login : <?=$log?></h4>
<a class="btn btn-info" id="changelog" href="#">Modifier  <span class="glyphicon glyphicon-cog"></span></a>
<form id="login" method="post">
	<div class="form-group">
		<input name="changelog" type="text">
		<button class="btn btn-danger"><span class="glyphicon glyphicon-ok-circle"></span></button>
	</div>
</form>
</div>
<div class="profItem">
<h4><span class="glyphicon glyphicon-star"></span>Mot de passe</h4>
<a class="btn btn-info" id="changemdp" href="#">Modifier  <span class="glyphicon glyphicon-cog"></span></a>
<form id="mdp" method="post">
	<div class="form-group">
		<input name="exmdp" type="password" placeholder="Mot de passe actuel">
		<input name="changemdp" type="password" placeholder="Nouveau mot de passe">
		<input name="checkmdp" type="password" placeholder="Confirmation">
		<button class="btn btn-danger"><span class="glyphicon glyphicon-ok-circle"></span></button>
	</div>
</form>
</div>

<div class="profItem">
<h4><span class="glyphicon glyphicon-star"></span>Email : <?=$email?></h4>
<a class="btn btn-info" id="changemail" href="#">Modifier  <span class="glyphicon glyphicon-cog"></span></a>
<form id="email" method="post">
	<div class="form-group">
		<input name="changemail" type="text">
		<button class="btn btn-danger"><span class="glyphicon glyphicon-ok-circle"></span></button>
	</div>
</form>
</div>

<div class="profItem">
<h4><span class="glyphicon glyphicon-star"></span>Date de naissance : <?=$birthdate?></h4>
<a class="btn btn-info" id="changedate" href="#">Modifier  <span class="glyphicon glyphicon-cog"></span></a>
<form id="birth" method="post">
	<div class="form-group">
		<input name="changedate" type="date">
		<button class="btn btn-danger"><span class="glyphicon glyphicon-ok-circle"></span></button>
	</div>
</form>
</div>
</section>
<section class="contribArt">
<h2><span class="glyphicon glyphicon-pencil"></span>Vos contributions <?=$contribution?></h2>
<div class="contribArt">
	 <?php require('./apps/display_profilArt.php'); ?>
</div>
<nav class="pages">
	<ul class="pagineur">
		<?php require('./apps/display_profilArtPagination.php'); ?>
	</ul>
</nav>
</section>
<section class="contribArt">
<h2><span class="glyphicon glyphicon-thumbs-up"></span>Vos commentaires <?=$commentaires?></h2>
<div class="contribArt">
	 <?php require('./apps/display_profilCom.php'); ?>
</div>
<nav class="pages">
	<ul class="pagineur">
		<?php require('./apps/display_profilComPagination.php'); ?>
	</ul>
</nav>
</section>