<form method="post" class="form-register">
	<div class="form-group">
		<label for="login">Login : </label>
		<input type="text" name="login" id="login" class="form-control" value="<?=$flogin?>">
	</div>
	<div class="form-group">
		<label for="email">E-mail : </label>
		<input type="text" name="email" id="email" class="form-control" value="<?=$email?>">
	</div>
	<div class="form-group">
		<label for="password">Mot de passe : </label>
		<input type="password" name="password" id="password" class="form-control">
		<input type="password" name="check-password" class="form-control" placeholder="Saisir le mot de passe une 2ème fois">
	</div>
	<button class="btn btn-default pull-right">s'inscrire</button>
	
	<div class="message form-group">
		<div class="bg-danger"><?=$error?></div>
		<div class="bg-success"><?=$success?></div>
	</div>
</form>