<form method="post" class="form-register">
	<div class="form-group">
		<label for="login">Login : </label>
		<input type="text" name="login" id="login" class="form-control" value="<?=$login?>">
	</div>
	<div class="form-group">
		<label for="email">E-mail : </label>
		<input type="text" name="email" id="email" class="form-control" value="<?=$email?>">
	</div>
	<div class="form-group">
		<label for="password">Mot de passe : </label>
		<input type="password" name="password" id="password" class="form-control">
		<input type="password" name="check-password" class="form-control">
	</div>
	<button>s'inscrire</button>
	
	<div class="message">
		<div class="error"><?=$error?></div>
		<div class="success"><?=$success?></div>
	</div>
</form>