<?php require('apps/search.php'); ?>
<div class="post-wrapp">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs--12">
		
			<h3><?=htmlentities($topic->getName())?></h3>
		</div>
		
	</div>
	<div class="row addPost">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs--12">
			<p>Ajouter une recette ?</p><?php require('views/createPost.phtml');?>
		</div>
		
	</div>
	<div class="row post">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs--12">
			<div class="searchResult">
			<?php require('apps/listPost_single.php');?>
			</div>
		</div>
	</div>
</div>

	
