<div class="row">
	
		<h3><?=htmlentities($topic->getName())?></h3>
	
</div>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 autor">
	<?php require('apps/memberPostForm.php');?>
	
	</div>
</div>
<div class="row">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 rules">

	<?php require('apps/listPost_single.php');?>
	
	</div>
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 infolastpost">
		
	</div>
</div>
