<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">		
		<base href="<?=$_SERVER['SCRIPT_NAME']?>" >
		<link rel="stylesheet/less" href="public/styles/mixins.less">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet/less" href="public/styles/style.less">
		<link rel="stylesheet/less" href="public/styles/style-admin.less">
		<!-- à laisser apres les fichiers .less -->
		<script src="public/scripts/less.min.js"></script> 
		<title>Cani-Goût</title>
	</head>
	<body>
		<div class="container-fluid">
			<?php require('./apps/header.php'); ?>
			<div class="container">
			<?php require('./apps/content.php'); ?>
			</div>
		</div>
		<script src="public/scripts/jquery-2.1.4.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<script src="public/scripts/script.js"></script>
		<script src="public/scripts/script-admin.js"></script>
	</body>
</html>