<div class="wrapper-tchat container-fluid">
	<div class="wrapper-tchat-title">
		<h2>Bienvenu sur le Tchat ! </h2>
	</div>
	<div class="wrapper-tchat-users row">
		<div class="tchat-users col-sm-3">
			<h3>Connectés</h3>
			<ul class="list-unstyled">
				<?php require('apps/display-tchat-users-online.php'); ?>
			</ul>
		</div>
		<div class="tchat-messages col-sm-9">
			<div class="tchat-histo">
				<!-- historique tchat -->
			</div>
			<div class="text-danger"><?=$error?></div>
			<div class="new-message">
				<input type="text" class="message form-control">
			</div>
		</div>
	</div>
</div>