<!-- <form class="form-horizontal" method="POST" action="apps/traitement_post.php">
	<h3>Modifier le commentaire</h3>
	  <div class="form-group form-group-lg">
		<div class="row">
		    <label class="col-sm-2 control-label" for="formGroupInputLarge">Titre (optionnel) </label>
		    <div class="col-sm-10">
		      <input class="form-control" type="text" id="updatepostTitle" name="updatepostTitle" value="<?=htmlentities($post->getTitle())?>" autofocus>
		      
		    </div>
		</div>
		<div class="row">
		    <label class="col-sm-2 control-label" for="formGroupInputLarge">Nouveau message </label>
		      <div class="col-sm-10">
		    	<textarea class="form-control" rows="3" name="updatepostContent" value="<?=htmlentities($post->getContent())?>"></textarea>
			</div>
		</div>
	</div>
		<div class="row">
			<div>
				<input type="submit" class="btn btn-default" name="validation" />
			</div>
		</div>
	</div>
</form> -->